### PR TITLE
Adding hebrew data, Hebrew font family and and example file

### PR DESCRIPTION
**Pull request by Udi-Fogiel**
Sorry it took so long, I was certain I sent the example file before...

### CODE REVIEW

**Comment by Udi-Fogiel** [comment]
It looks like there is a typo in the Estonian quotation marks deceleration.  The following code does not compile:
```
\etlang \quotes
\bye
```

**Comment by olsak** [comment]
Thank you very much. Is it ready to commit this to the main branch or you are still working on it?

Please, add an information to the file demo/op/letter-he.tex that this file is prepared by you.

**Comment by Udi-Fogiel** [comment]
> Thank you very much. Is it ready to commit this to the main branch or you are still working on it?
I've finished working on it.
> Please, add an information to the file demo/op/letter-he.tex that this file is prepared by you.
Done, I've also added a comment in the font family file about the fact that the script feature is hebr
by default.

**Comment by olsak** [comment]
Thank you again.

**Pull request merged**
